# Generated by Django 4.0.2 on 2022-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanmaker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condiments',
        ),
    ]
