# Generated by Django 4.0.2 on 2022-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanmaker', '0002_delete_condiments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='ingredients',
            field=models.TextField(default='', max_length=400),
        ),
    ]
