# Generated by Django 4.0.2 on 2022-03-04 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanmaker', '0003_meals_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(max_length=10)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanmaker.meals')),
                ('mealuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
